import { NextPage } from "next";
import Head from "next/head";
import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";
import { useEffect } from "react";

const Index: NextPage = () => {
  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await fetch("https://genshinlist.com/api/characters");
        if (!response.ok) {
          throw new Error("Failed to fetch data");
        }
        const data = await response.json();
        console.log(data);
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    };

    fetchData();
  }, []);
  return (
    <>
      <Head>
        <title>genshin-store</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <h1>Hello</h1>
      <LandingPageTemplate />
    </>
  );
};

export default Index;
